---
- name: Install python
  hosts: all
  remote_user: ansible 
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible 
  roles:
  - common

- name: Install docker on nodes
  hosts: all
  remote_user: ansible 
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: Get all images from the sozialarchiv
  hosts: all
  remote_user: ansible 
  roles:
  - data

- name: Install iiif server and start it
  vars:
    domain: dataramblers.io
  hosts: all
  remote_user:  ansible
  roles:
  - dockercontainers
