---
- name: Install python
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
# basic config
- name: apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
  - common
# install docker and co
- name: Install docker on nodes
  hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
# load all data from sah or any other data provider
- name: Get all images from the sozialarchiv
  hosts: all
  become: yes
  roles:
  - data
# load and start the docker containers
- name: Install iiif server and start it
  hosts: all
  become: yes
  roles:
  - dockercontainers
